version: '3.8'

services:
  api:
    build: .
    container_name: api-buhardilla
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    # Descomentar si quieres que Docker 
    # levante también la base de datos de PostgreSQL
    # depends_on:
    #   - db

    # db:
    #   image: postgres:15-alpine
    #   container_name: postgres-buhardilla
    #   environment:
    #     POSTGRES_USER: tu_usuario
    #     POSTGRES_PASSWORD: tu_password
    #     POSTGRES_DB: tu_base_de_datos
    #   ports:
    #     - "5432:5432"
    #   volumes:
    #     - pgdata:/var/lib/postgresql/data
    #   restart: unless-stopped

volumes:
  pgdata:
