-- DROPS
DROP TABLE IF EXISTS games CASCADE;

DROP TABLE IF EXISTS collections_videogames CASCADE;

DROP TABLE IF EXISTS collections_users CASCADE;

DROP TABLE IF EXISTS platforms_videogames CASCADE;

DROP TABLE IF EXISTS companies_videogames CASCADE;

DROP TABLE IF EXISTS platforms_users CASCADE;

DROP TABLE IF EXISTS collections CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS videogames CASCADE;

DROP TABLE IF EXISTS companies CASCADE;

DROP TABLE IF EXISTS platforms CASCADE;

DROP TABLE IF EXISTS paises CASCADE;

-- Tablas

CREATE TABLE paises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iso CHAR(2),
    nombre VARCHAR(80)
);

INSERT INTO
    paises
VALUES (1, 'AF', 'Afganistán'),
    (2, 'AX', 'Islas Gland'),
    (3, 'AL', 'Albania'),
    (4, 'DE', 'Alemania'),
    (5, 'AD', 'Andorra'),
    (6, 'AO', 'Angola'),
    (7, 'AI', 'Anguilla'),
    (8, 'AQ', 'Antártida'),
    (9, 'AG', 'Antigua y Barbuda'),
    (
        10,
        'AN',
        'Antillas Holandesas'
    ),
    (11, 'SA', 'Arabia Saudí'),
    (12, 'DZ', 'Argelia'),
    (13, 'AR', 'Argentina'),
    (14, 'AM', 'Armenia'),
    (15, 'AW', 'Aruba'),
    (16, 'AU', 'Australia'),
    (17, 'AT', 'Austria'),
    (18, 'AZ', 'Azerbaiyán'),
    (19, 'BS', 'Bahamas'),
    (20, 'BH', 'Bahréin'),
    (21, 'BD', 'Bangladesh'),
    (22, 'BB', 'Barbados'),
    (23, 'BY', 'Bielorrusia'),
    (24, 'BE', 'Bélgica'),
    (25, 'BZ', 'Belice'),
    (26, 'BJ', 'Benin'),
    (27, 'BM', 'Bermudas'),
    (28, 'BT', 'Bhután'),
    (29, 'BO', 'Bolivia'),
    (
        30,
        'BA',
        'Bosnia y Herzegovina'
    ),
    (31, 'BW', 'Botsuana'),
    (32, 'BV', 'Isla Bouvet'),
    (33, 'BR', 'Brasil'),
    (34, 'BN', 'Brunéi'),
    (35, 'BG', 'Bulgaria'),
    (36, 'BF', 'Burkina Faso'),
    (37, 'BI', 'Burundi'),
    (38, 'CV', 'Cabo Verde'),
    (39, 'KY', 'Islas Caimán'),
    (40, 'KH', 'Camboya'),
    (41, 'CM', 'Camerún'),
    (42, 'CA', 'Canadá'),
    (
        43,
        'CF',
        'República Centroafricana'
    ),
    (44, 'TD', 'Chad'),
    (45, 'CZ', 'República Checa'),
    (46, 'CL', 'Chile'),
    (47, 'CN', 'China'),
    (48, 'CY', 'Chipre'),
    (49, 'CX', 'Isla de Navidad'),
    (
        50,
        'VA',
        'Ciudad del Vaticano'
    ),
    (51, 'CC', 'Islas Cocos'),
    (52, 'CO', 'Colombia'),
    (53, 'KM', 'Comoras'),
    (
        54,
        'CD',
        'República Democrática del Congo'
    ),
    (55, 'CG', 'Congo'),
    (56, 'CK', 'Islas Cook'),
    (57, 'KP', 'Corea del Norte'),
    (58, 'KR', 'Corea del Sur'),
    (59, 'CI', 'Costa de Marfil'),
    (60, 'CR', 'Costa Rica'),
    (61, 'HR', 'Croacia'),
    (62, 'CU', 'Cuba'),
    (63, 'DK', 'Dinamarca'),
    (64, 'DM', 'Dominica'),
    (
        65,
        'DO',
        'República Dominicana'
    ),
    (66, 'EC', 'Ecuador'),
    (67, 'EG', 'Egipto'),
    (68, 'SV', 'El Salvador'),
    (
        69,
        'AE',
        'Emiratos Árabes Unidos'
    ),
    (70, 'ER', 'Eritrea'),
    (71, 'SK', 'Eslovaquia'),
    (72, 'SI', 'Eslovenia'),
    (73, 'ES', 'España'),
    (
        74,
        'UM',
        'Islas ultramarinas de Estados Unidos'
    ),
    (75, 'US', 'Estados Unidos'),
    (76, 'EE', 'Estonia'),
    (77, 'ET', 'Etiopía'),
    (78, 'FO', 'Islas Feroe'),
    (79, 'PH', 'Filipinas'),
    (80, 'FI', 'Finlandia'),
    (81, 'FJ', 'Fiyi'),
    (82, 'FR', 'Francia'),
    (83, 'GA', 'Gabón'),
    (84, 'GM', 'Gambia'),
    (85, 'GE', 'Georgia'),
    (
        86,
        'GS',
        'Islas Georgias del Sur y Sandwich del Sur'
    ),
    (87, 'GH', 'Ghana'),
    (88, 'GI', 'Gibraltar'),
    (89, 'GD', 'Granada'),
    (90, 'GR', 'Grecia'),
    (91, 'GL', 'Groenlandia'),
    (92, 'GP', 'Guadalupe'),
    (93, 'GU', 'Guam'),
    (94, 'GT', 'Guatemala'),
    (95, 'GF', 'Guayana Francesa'),
    (96, 'GN', 'Guinea'),
    (97, 'GQ', 'Guinea Ecuatorial'),
    (98, 'GW', 'Guinea-Bissau'),
    (99, 'GY', 'Guyana'),
    (100, 'HT', 'Haití'),
    (
        101,
        'HM',
        'Islas Heard y McDonald'
    ),
    (102, 'HN', 'Honduras'),
    (103, 'HK', 'Hong Kong'),
    (104, 'HU', 'Hungría'),
    (105, 'IN', 'India'),
    (106, 'ID', 'Indonesia'),
    (107, 'IR', 'Irán'),
    (108, 'IQ', 'Iraq'),
    (109, 'IE', 'Irlanda'),
    (110, 'IS', 'Islandia'),
    (111, 'IL', 'Israel'),
    (112, 'IT', 'Italia'),
    (113, 'JM', 'Jamaica'),
    (114, 'JP', 'Japón'),
    (115, 'JO', 'Jordania'),
    (116, 'KZ', 'Kazajstán'),
    (117, 'KE', 'Kenia'),
    (118, 'KG', 'Kirguistán'),
    (119, 'KI', 'Kiribati'),
    (120, 'KW', 'Kuwait'),
    (121, 'LA', 'Laos'),
    (122, 'LS', 'Lesotho'),
    (123, 'LV', 'Letonia'),
    (124, 'LB', 'Líbano'),
    (125, 'LR', 'Liberia'),
    (126, 'LY', 'Libia'),
    (127, 'LI', 'Liechtenstein'),
    (128, 'LT', 'Lituania'),
    (129, 'LU', 'Luxemburgo'),
    (130, 'MO', 'Macao'),
    (131, 'MK', 'ARY Macedonia'),
    (132, 'MG', 'Madagascar'),
    (133, 'MY', 'Malasia'),
    (134, 'MW', 'Malawi'),
    (135, 'MV', 'Maldivas'),
    (136, 'ML', 'Malí'),
    (137, 'MT', 'Malta'),
    (138, 'FK', 'Islas Malvinas'),
    (
        139,
        'MP',
        'Islas Marianas del Norte'
    ),
    (140, 'MA', 'Marruecos'),
    (141, 'MH', 'Islas Marshall'),
    (142, 'MQ', 'Martinica'),
    (143, 'MU', 'Mauricio'),
    (144, 'MR', 'Mauritania'),
    (145, 'YT', 'Mayotte'),
    (146, 'MX', 'México'),
    (147, 'FM', 'Micronesia'),
    (148, 'MD', 'Moldavia'),
    (149, 'MC', 'Mónaco'),
    (150, 'MN', 'Mongolia'),
    (151, 'MS', 'Montserrat'),
    (152, 'MZ', 'Mozambique'),
    (153, 'MM', 'Myanmar'),
    (154, 'NA', 'Namibia'),
    (155, 'NR', 'Nauru'),
    (156, 'NP', 'Nepal'),
    (157, 'NI', 'Nicaragua'),
    (158, 'NE', 'Níger'),
    (159, 'NG', 'Nigeria'),
    (160, 'NU', 'Niue'),
    (161, 'NF', 'Isla Norfolk'),
    (162, 'NO', 'Noruega'),
    (163, 'NC', 'Nueva Caledonia'),
    (164, 'NZ', 'Nueva Zelanda'),
    (165, 'OM', 'Omán'),
    (166, 'NL', 'Países Bajos'),
    (167, 'PK', 'Pakistán'),
    (168, 'PW', 'Palau'),
    (169, 'PS', 'Palestina'),
    (170, 'PA', 'Panamá'),
    (
        171,
        'PG',
        'Papúa Nueva Guinea'
    ),
    (172, 'PY', 'Paraguay'),
    (173, 'PE', 'Perú'),
    (174, 'PN', 'Islas Pitcairn'),
    (
        175,
        'PF',
        'Polinesia Francesa'
    ),
    (176, 'PL', 'Polonia'),
    (177, 'PT', 'Portugal'),
    (178, 'PR', 'Puerto Rico'),
    (179, 'QA', 'Qatar'),
    (180, 'GB', 'Reino Unido'),
    (181, 'RE', 'Reunión'),
    (182, 'RW', 'Ruanda'),
    (183, 'RO', 'Rumania'),
    (184, 'RU', 'Rusia'),
    (
        185,
        'EH',
        'Sahara Occidental'
    ),
    (186, 'SB', 'Islas Salomón'),
    (187, 'WS', 'Samoa'),
    (188, 'AS', 'Samoa Americana'),
    (
        189,
        'KN',
        'San Cristóbal y Nevis'
    ),
    (190, 'SM', 'San Marino'),
    (
        191,
        'PM',
        'San Pedro y Miquelón'
    ),
    (
        192,
        'VC',
        'San Vicente y las Granadinas'
    ),
    (193, 'SH', 'Santa Helena'),
    (194, 'LC', 'Santa Lucía'),
    (
        195,
        'ST',
        'Santo Tomé y Príncipe'
    ),
    (196, 'SN', 'Senegal'),
    (
        197,
        'CS',
        'Serbia y Montenegro'
    ),
    (198, 'SC', 'Seychelles'),
    (199, 'SL', 'Sierra Leona'),
    (200, 'SG', 'Singapur'),
    (201, 'SY', 'Siria'),
    (202, 'SO', 'Somalia'),
    (203, 'LK', 'Sri Lanka'),
    (204, 'SZ', 'Suazilandia'),
    (205, 'ZA', 'Sudáfrica'),
    (206, 'SD', 'Sudán'),
    (207, 'SE', 'Suecia'),
    (208, 'CH', 'Suiza'),
    (209, 'SR', 'Surinam'),
    (
        210,
        'SJ',
        'Svalbard y Jan Mayen'
    ),
    (211, 'TH', 'Tailandia'),
    (212, 'TW', 'Taiwán'),
    (213, 'TZ', 'Tanzania'),
    (214, 'TJ', 'Tayikistán'),
    (
        215,
        'IO',
        'Territorio Británico del Océano Índico'
    ),
    (
        216,
        'TF',
        'Territorios Australes Franceses'
    ),
    (217, 'TL', 'Timor Oriental'),
    (218, 'TG', 'Togo'),
    (219, 'TK', 'Tokelau'),
    (220, 'TO', 'Tonga'),
    (
        221,
        'TT',
        'Trinidad y Tobago'
    ),
    (222, 'TN', 'Túnez'),
    (
        223,
        'TC',
        'Islas Turcas y Caicos'
    ),
    (224, 'TM', 'Turkmenistán'),
    (225, 'TR', 'Turquía'),
    (226, 'TV', 'Tuvalu'),
    (227, 'UA', 'Ucrania'),
    (228, 'UG', 'Uganda'),
    (229, 'UY', 'Uruguay'),
    (230, 'UZ', 'Uzbekistán'),
    (231, 'VU', 'Vanuatu'),
    (232, 'VE', 'Venezuela'),
    (233, 'VN', 'Vietnam'),
    (
        234,
        'VG',
        'Islas Vírgenes Británicas'
    ),
    (
        235,
        'VI',
        'Islas Vírgenes de los Estados Unidos'
    ),
    (236, 'WF', 'Wallis y Futuna'),
    (237, 'YE', 'Yemen'),
    (238, 'DJ', 'Yibuti'),
    (239, 'ZM', 'Zambia'),
    (240, 'ZW', 'Zimbabue');

CREATE TABLE platforms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO
    platforms (name)
VALUES ('Magnavox Odyssey (1972)'),
    ('Philips Odyssey series'),
    ('Philips Tele-Spiel'),
    ('Coleco Telstar series'),
    ('Binatone TV Master'),
    ('Interton Video 2000'),
    ('Radiola TV-Game'),
    ('Hanimex Pong'),
    ('Atari Pong'),
    ('Sears Tele-Games'),
    ('Atari 2600'),
    ('Atari 5200'),
    ('Magnavox Odyssey²'),
    ('Intellivision'),
    ('ColecoVision'),
    ('Fairchild Channel F'),
    ('RCA Studio II'),
    ('Bally Astrocade'),
    ('Emerson Arcadia 2001'),
    ('APF-MP1000'),
    ('Vectrex'),
    ('VC 4000'),
    ('Epoch Cassette Vision'),
    ('Mattel Aquarius'),
    (
        'Nintendo Entertainment System (NES)'
    ),
    ('Famicom'),
    ('Sega Master System'),
    ('Atari 7800'),
    ('Atari XEGS'),
    ('Amstrad GX4000'),
    ('SNK Alpha Denshi'),
    ('Sharp Twin Famicom'),
    ('Super Nintendo (SNES)'),
    ('Super Famicom'),
    ('Sega Mega Drive / Genesis'),
    ('Neo Geo AES'),
    ('Neo Geo CD'),
    ('TurboGrafx-16 / PC Engine'),
    ('PC Engine Duo'),
    ('Commodore CDTV'),
    ('Philips CD-i'),
    ('FM Towns Marty'),
    ('PlayStation'),
    ('Nintendo 64'),
    ('Sega Saturn'),
    ('Atari Jaguar'),
    ('Atari Jaguar CD'),
    ('3DO Interactive Multiplayer'),
    ('Amiga CD32'),
    ('Apple Pippin'),
    ('Casio Loopy'),
    ('Bandai Playdia'),
    ('PlayStation 2'),
    ('Nintendo GameCube'),
    ('Xbox'),
    ('Sega Dreamcast'),
    ('Panasonic Q'),
    ('iQue Player'),
    ('PlayStation 3'),
    ('Xbox 360'),
    ('Nintendo Wii'),
    ('Ouya'),
    ('Zeebo'),
    ('OnLive MicroConsole'),
    ('PlayStation 4'),
    ('Xbox One'),
    ('Wii U'),
    ('Steam Machine'),
    ('NVIDIA Shield TV'),
    ('PlayStation TV'),
    ('PlayStation 5'),
    ('Xbox Series X'),
    ('Xbox Series S'),
    ('Nintendo Switch'),
    ('Microvision'),
    ('Game & Watch'),
    ('Nintendo Game Boy'),
    ('Game Boy Pocket'),
    ('Game Boy Color'),
    ('Game Boy Advance'),
    ('Game Boy Advance SP'),
    ('Game Boy Micro'),
    ('Nintendo DS'),
    ('Nintendo DS Lite'),
    ('Nintendo DSi'),
    ('Nintendo DSi XL'),
    ('Nintendo 3DS'),
    ('New Nintendo 3DS'),
    ('Nintendo 2DS'),
    ('PlayStation Portable (PSP)'),
    ('PlayStation Vita'),
    ('Sega Game Gear'),
    ('Sega Nomad'),
    ('Atari Lynx'),
    ('Neo Geo Pocket'),
    ('Neo Geo Pocket Color'),
    ('Wonderswan'),
    ('Wonderswan Color'),
    ('Tapwave Zodiac'),
    ('Gizmondo'),
    ('GP32'),
    ('GP2X'),
    ('Dingoo A320'),
    ('Steam Deck'),
    ('ASUS ROG Ally'),
    ('AYANEO series'),
    ('VTech CreatiVision'),
    ('VTech Socrates'),
    ('Leapster'),
    ('Leapster Explorer'),
    ('Pico (Sega)'),
    ('Casio PV-1000'),
    ('Nintendo Color TV-Game'),
    ('Virtual Boy'),
    ('Atari Panther (cancelada)'),
    ('Sega Pluto (cancelada)'),
    ('Neo Geo X'),
    ('Intellivision Amico'),
    ('Google Stadia (hardware)'),
    ('Amazon Luna Controller'),
    ('Playdate'),
    ('Evercade')
on CONFLICT (name) DO NOTHING;

CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    country_id BIGINT REFERENCES paises (id) ON DELETE SET NULL
);

INSERT INTO
    companies (name, country_id)
VALUES ('Atari', 75),
    ('Sega', 114),
    ('Nintendo', 114),
    ('Electronic Arts', 75),
    ('Ubisoft', 82),
    ('Capcom', 114),
    ('Square Enix', 114),
    (
        'Sony Interactive Entertainment',
        114
    ),
    ('Microsoft Gaming', 75),
    ('Valve', 75),
    ('Bethesda Game Studios', 75),
    ('Rockstar Games', 75),
    ('CD Projekt Red', 176),
    ('Supergiant Games', 75),
    ('FromSoftware', 114);

CREATE TABLE videogames (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    cover VARCHAR(255) DEFAULT "",
    genre VARCHAR(100),
    note NUMERIC(3, 1) CHECK (note BETWEEN 0 AND 10)
);

INSERT INTO
    videogames (name, genre, note)
VALUES (
        'Elden Ring',
        'Action RPG',
        9.6
    ),
    (
        'Cyberpunk 2077',
        'Open World RPG',
        8.5
    ),
    (
        'The Legend of Zelda: Tears of the Kingdom',
        'Adventure',
        9.7
    ),
    ('Hades', 'Roguelike', 9.3),
    (
        'Red Dead Redemption 2',
        'Action-Adventure',
        9.8
    );

CREATE TABLE companies_videogames (
    company_id BIGINT REFERENCES companies (id) ON DELETE CASCADE,
    videogame_id BIGINT REFERENCES videogames (id) ON DELETE CASCADE,
    PRIMARY KEY (company_id, videogame_id)
);

INSERT INTO
    companies_videogames (company_id, videogame_id)
VALUES (
        (
            SELECT id
            FROM companies
            WHERE
                name = 'FromSoftware'
        ),
        (
            SELECT id
            FROM videogames
            WHERE
                name = 'Elden Ring'
        )
    ),
    (
        (
            SELECT id
            FROM companies
            WHERE
                name = 'CD Projekt Red'
        ),
        (
            SELECT id
            FROM videogames
            WHERE
                name = 'Cyberpunk 2077'
        )
    ),
    (
        (
            SELECT id
            FROM companies
            WHERE
                name = 'Nintendo'
        ),
        (
            SELECT id
            FROM videogames
            WHERE
                name = 'The Legend of Zelda: Tears of the Kingdom'
        )
    ),
    (
        (
            SELECT id
            FROM companies
            WHERE
                name = 'Supergiant Games'
        ),
        (
            SELECT id
            FROM videogames
            WHERE
                name = 'Hades'
        )
    ),
    (
        (
            SELECT id
            FROM companies
            WHERE
                name = 'Rockstar Games'
        ),
        (
            SELECT id
            FROM videogames
            WHERE
                name = 'Red Dead Redemption 2'
        )
    );

CREATE TABLE platforms_videogames (
    platform_id BIGINT REFERENCES platforms (id) ON DELETE CASCADE,
    videogame_id BIGINT REFERENCES videogames (id) ON DELETE CASCADE,
    PRIMARY KEY (platform_id, videogame_id)
);

INSERT INTO
    platforms_videogames (platform_id, videogame_id)
SELECT p.id, v.id
FROM platforms p, videogames v
WHERE
    p.name IN (
        'PlayStation 5',
        'Xbox Series X',
        'Xbox Series S'
    )
    AND v.name = 'Elden Ring';

INSERT INTO
    platforms_videogames (platform_id, videogame_id)
SELECT p.id, v.id
FROM platforms p, videogames v
WHERE
    p.name IN ('PlayStation 4', 'Xbox One')
    AND v.name = 'Red Dead Redemption 2';

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100),
    uuid VARCHAR(100) UNIQUE
);

INSERT INTO
    users (email, password, name, uuid)
VALUES (
        'martinlopezpablo@gmail.com',
        '$2b$12$hash_simulado',
        'Pablo',
        'KGH08jtOucUSoq7uCVpKxuQfcbp1'
    );

CREATE TABLE collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE collections_users (
    collection_id BIGINT REFERENCES collections (id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (collection_id, user_id)
);

CREATE TABLE collections_videogames (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id BIGINT REFERENCES collections (id) ON DELETE CASCADE,
    videogame_id BIGINT REFERENCES videogames (id) ON DELETE CASCADE
);

CREATE TABLE platforms_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_id BIGINT REFERENCES platforms (id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    UNIQUE (platform_id, user_id)
);

INSERT INTO
    platforms_users (platform_id, user_id)
SELECT p.id, u.id
FROM platforms p, users u
WHERE
    u.email = 'martinlopezpablo@gmail.com'
    AND p.name IN (
        'PlayStation 5',
        'Nintendo Switch',
        'PC'
    );

CREATE TABLE games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    videogame_id BIGINT REFERENCES videogames (id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    platform_id BIGINT NOT NULL REFERENCES platforms (id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    complete BOOLEAN DEFAULT FALSE,
    note NUMERIC(3, 1) CHECK (note BETWEEN 0 AND 10),
    total_time VARCHAR(50),
    player_notes TEXT,
    UNIQUE (videogame_id, user_id)
);

INSERT INTO
    games (
        videogame_id,
        user_id,
        platform_id,
        complete,
        note,
        total_time,
        player_notes
    )
VALUES (
        (
            SELECT id
            FROM videogames
            WHERE
                name = 'Elden Ring'
        ),
        (
            SELECT id
            FROM users
            WHERE
                email = 'martinlopezpablo@gmail.com'
        ),
        (
            SELECT id
            FROM platforms
            WHERE
                name = 'PlayStation 5'
        ),
        true,
        9.5,
        '120h',
        'Una obra maestra, muy desafiante'
    ),
    (
        (
            SELECT id
            FROM videogames
            WHERE
                name = 'Hades'
        ),
        (
            SELECT id
            FROM users
            WHERE
                email = 'martinlopezpablo@gmail.com'
        ),
        (
            SELECT id
            FROM platforms
            WHERE
                name = 'Nintendo Switch'
        ),
        true,
        9.2,
        '45h',
        'Gameplay perfecto y música increíble'
    );